application: wukong-demo
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /mapreduce(/.*)?
  script: $PYTHON_LIB/google/appengine/ext/mapreduce/main.py

- url: /.*
  script: wukong-demo.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

includes:
- mapreduce/include.yaml
